#!/bin/bash
# update-version.sh -- created 2016-05-16, Renato Alves
# @Last Change: 2016-05-16.
# @Revision:    0.1

echo -e "# Autogenerated from git tags using update-version.sh\n__version__ = \"$(git describe --tags)\"" > simpletap/version.py

# vi: 
